import RH.Program

/-! The register-machine program actually emitted by the compiler for
    machines/2026-riemann-rh-370/riemann.nql: one instruction per program-counter
    slot (pc_bits = 9, 512 slots), with jump targets made absolute.  Extracted
    from the compiler's subroutine child maps; `pad` marks slots inside
    multi-slot no-ops that are never dispatched.
    Registers: 0=_Glcm, 1=_Gx, 2=_Gc, 3=_copysave, 4=_scratch_1, 5=_scratch_2, 6=_Gi, 7=_Gdenom, 8=_Gj, 9=_Gk, 10=_Gl -/

namespace IR370

inductive Instr where
  | inc (r : Nat) | dec (r : Nat) | jmp (t : Nat) | noop (k : Nat) | init | halt | pad
  deriving Repr, DecidableEq

def prog : Array Instr := #[
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.init,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 0,
  Instr.jmp 23,
  Instr.jmp 20,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 0,
  Instr.inc 0,
  Instr.inc 1,
  Instr.dec 2,
  Instr.jmp 31,
  Instr.jmp 28,
  Instr.noop 0,
  Instr.dec 0,
  Instr.jmp 37,
  Instr.inc 2,
  Instr.inc 3,
  Instr.jmp 32,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 48,
  Instr.inc 0,
  Instr.jmp 44,
  Instr.dec 0,
  Instr.jmp 53,
  Instr.inc 3,
  Instr.inc 5,
  Instr.jmp 48,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 64,
  Instr.inc 0,
  Instr.jmp 60,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 5,
  Instr.jmp 119,
  Instr.inc 5,
  Instr.noop 0,
  Instr.dec 1,
  Instr.jmp 77,
  Instr.inc 3,
  Instr.inc 4,
  Instr.jmp 72,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 88,
  Instr.inc 1,
  Instr.jmp 84,
  Instr.dec 4,
  Instr.jmp 68,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 5,
  Instr.jmp 97,
  Instr.jmp 88,
  Instr.jmp 119,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 4,
  Instr.jmp 103,
  Instr.jmp 100,
  Instr.noop 0,
  Instr.dec 2,
  Instr.jmp 109,
  Instr.inc 0,
  Instr.inc 3,
  Instr.jmp 104,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 116,
  Instr.inc 2,
  Instr.jmp 112,
  Instr.noop 0,
  Instr.jmp 48,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 6,
  Instr.jmp 123,
  Instr.jmp 120,
  Instr.noop 0,
  Instr.noop 0,
  Instr.inc 6,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 7,
  Instr.jmp 131,
  Instr.jmp 128,
  Instr.noop 0,
  Instr.noop 0,
  Instr.inc 7,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 0,
  Instr.jmp 141,
  Instr.inc 8,
  Instr.inc 3,
  Instr.jmp 136,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 152,
  Instr.inc 0,
  Instr.jmp 148,
  Instr.dec 1,
  Instr.jmp 157,
  Instr.inc 9,
  Instr.inc 3,
  Instr.jmp 152,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 164,
  Instr.inc 1,
  Instr.jmp 160,
  Instr.dec 8,
  Instr.jmp 279,
  Instr.inc 8,
  Instr.dec 8,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 2,
  Instr.jmp 189,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 6,
  Instr.jmp 181,
  Instr.inc 3,
  Instr.inc 4,
  Instr.jmp 176,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 188,
  Instr.inc 6,
  Instr.jmp 184,
  Instr.jmp 169,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 4,
  Instr.jmp 196,
  Instr.inc 2,
  Instr.jmp 192,
  Instr.dec 10,
  Instr.jmp 214,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 6,
  Instr.jmp 205,
  Instr.inc 3,
  Instr.inc 4,
  Instr.jmp 200,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 212,
  Instr.inc 6,
  Instr.jmp 208,
  Instr.jmp 196,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 7,
  Instr.jmp 221,
  Instr.inc 3,
  Instr.inc 4,
  Instr.jmp 216,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 228,
  Instr.inc 7,
  Instr.jmp 224,
  Instr.dec 4,
  Instr.jmp 232,
  Instr.inc 10,
  Instr.jmp 228,
  Instr.noop 0,
  Instr.dec 9,
  Instr.jmp 252,
  Instr.noop 0,
  Instr.dec 2,
  Instr.jmp 239,
  Instr.jmp 236,
  Instr.noop 0,
  Instr.dec 10,
  Instr.jmp 245,
  Instr.inc 2,
  Instr.inc 3,
  Instr.jmp 240,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 252,
  Instr.inc 10,
  Instr.jmp 248,
  Instr.dec 7,
  Instr.jmp 269,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 6,
  Instr.jmp 261,
  Instr.inc 3,
  Instr.inc 4,
  Instr.jmp 256,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 268,
  Instr.inc 6,
  Instr.jmp 264,
  Instr.jmp 252,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 4,
  Instr.jmp 276,
  Instr.inc 7,
  Instr.jmp 272,
  Instr.inc 6,
  Instr.jmp 164,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 7,
  Instr.jmp 285,
  Instr.inc 3,
  Instr.inc 5,
  Instr.jmp 280,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 292,
  Instr.inc 7,
  Instr.jmp 288,
  Instr.noop 0,
  Instr.dec 5,
  Instr.jmp 310,
  Instr.noop 0,
  Instr.dec 1,
  Instr.jmp 301,
  Instr.inc 3,
  Instr.inc 4,
  Instr.jmp 296,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 308,
  Instr.inc 1,
  Instr.jmp 304,
  Instr.jmp 292,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 4,
  Instr.jmp 317,
  Instr.dec 10,
  Instr.noop 0,
  Instr.jmp 312,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 2,
  Instr.jmp 325,
  Instr.inc 4,
  Instr.inc 5,
  Instr.jmp 320,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 4,
  Instr.jmp 349,
  Instr.noop 1,
  Instr.pad,
  Instr.noop 2,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.dec 5,
  Instr.jmp 341,
  Instr.inc 2,
  Instr.inc 3,
  Instr.jmp 336,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 348,
  Instr.inc 5,
  Instr.jmp 344,
  Instr.jmp 328,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 5,
  Instr.jmp 355,
  Instr.jmp 352,
  Instr.noop 0,
  Instr.dec 10,
  Instr.jmp 374,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 7,
  Instr.jmp 365,
  Instr.inc 3,
  Instr.inc 4,
  Instr.jmp 360,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 372,
  Instr.inc 7,
  Instr.jmp 368,
  Instr.jmp 356,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 4,
  Instr.jmp 380,
  Instr.inc 10,
  Instr.jmp 376,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 2,
  Instr.jmp 389,
  Instr.inc 4,
  Instr.inc 5,
  Instr.jmp 384,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 4,
  Instr.jmp 413,
  Instr.noop 1,
  Instr.pad,
  Instr.noop 2,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.dec 5,
  Instr.jmp 405,
  Instr.inc 2,
  Instr.inc 3,
  Instr.jmp 400,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 412,
  Instr.inc 5,
  Instr.jmp 408,
  Instr.jmp 392,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 5,
  Instr.jmp 419,
  Instr.jmp 416,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 2,
  Instr.jmp 438,
  Instr.noop 0,
  Instr.dec 1,
  Instr.jmp 429,
  Instr.inc 3,
  Instr.inc 4,
  Instr.jmp 424,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 436,
  Instr.inc 1,
  Instr.jmp 432,
  Instr.jmp 420,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 4,
  Instr.jmp 444,
  Instr.inc 2,
  Instr.jmp 440,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 10,
  Instr.jmp 453,
  Instr.inc 4,
  Instr.inc 5,
  Instr.jmp 448,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 4,
  Instr.jmp 477,
  Instr.noop 1,
  Instr.pad,
  Instr.noop 2,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.dec 5,
  Instr.jmp 469,
  Instr.inc 10,
  Instr.inc 3,
  Instr.jmp 464,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 3,
  Instr.jmp 476,
  Instr.inc 5,
  Instr.jmp 472,
  Instr.jmp 456,
  Instr.noop 0,
  Instr.noop 1,
  Instr.pad,
  Instr.dec 5,
  Instr.jmp 483,
  Instr.jmp 480,
  Instr.noop 0,
  Instr.dec 2,
  Instr.jmp 489,
  Instr.dec 10,
  Instr.jmp 27,
  Instr.jmp 484,
  Instr.noop 0,
  Instr.noop 0,
  Instr.noop 0,
  Instr.dec 10,
  Instr.jmp 27,
  Instr.halt,
  Instr.jmp 27,
  Instr.noop 4,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.pad,
  Instr.pad
]

structure St where
  pc : Nat
  regs : Array Nat
  halted : Bool
  deriving Repr

def nregs : Nat := 11

def start : St := ⟨0, Array.replicate nregs 0, false⟩

/-- One instruction.  `dec` skips the next slot when the register was nonzero
    (the compiler's branch convention); `noop k` advances by `2^k`;
    `init` is a register-storage initializer, a no-op at this level. -/
def step (s : St) : St :=
  if s.halted then s else
  match prog.getD s.pc Instr.pad with
  | Instr.inc r  => { s with pc := s.pc + 1, regs := s.regs.set! r (s.regs.getD r 0 + 1) }
  | Instr.dec r  => if s.regs.getD r 0 = 0 then { s with pc := s.pc + 1 }
                    else { s with pc := s.pc + 2, regs := s.regs.set! r (s.regs.getD r 0 - 1) }
  | Instr.jmp t  => { s with pc := t }
  | Instr.noop k => { s with pc := s.pc + 2 ^ k }
  | Instr.init   => { s with pc := s.pc + 1 }
  | Instr.halt   => { s with halted := true }
  | Instr.pad    => { s with halted := true }   -- never reached; treated as stuck

def run : Nat → St → St
  | 0, s => s
  | k+1, s => run k (step s)

/-- The outer loop head is slot 27 (`x = x + 1`).  Collect the register
    vectors at the first `m` arrivals there within `budget` steps. -/
def headsAux : Nat → Nat → St → List (Array Nat) → List (Array Nat)
  | 0, _, _, acc => acc.reverse
  | budget+1, m, s, acc =>
    if m = 0 then acc.reverse else
    let acc' := if s.pc = 27 && !s.halted then s.regs :: acc else acc
    let m' := if s.pc = 27 && !s.halted then m - 1 else m
    headsAux budget m' (step s) acc'

def heads (m budget : Nat) : List (Array Nat) := headsAux budget m start []

/-- Registers: 0=lcm 1=x 2=c 3=copysave 4=scratch1 5=scratch2 6=i 7=denom 8=j 9=k 10=l.
    At the n-th arrival at the loop head the model predicts x = n-1,
    lcm = lcmUpTo (n-1), and l = j = k = 0 (the zero-invariants). -/
def headOk (n : Nat) (r : Array Nat) : Bool :=
  r.getD 1 0 == n - 1 && r.getD 0 0 == RHProg.lcmUpTo (n - 1) &&
  r.getD 10 0 == 0 && r.getD 8 0 == 0 && r.getD 9 0 == 0 &&
  r.getD 3 0 == 0 && r.getD 4 0 == 0 && r.getD 5 0 == 0

/-- Machine-checked: the compiled program reaches the loop head three times
    within 60000 steps, each time with registers as the model predicts. -/
theorem heads_ok : (heads 3 60000).length = 3 ∧
    (List.range 3).all (fun i => headOk (i+1) ((heads 3 60000).getD i #[])) = true := by
  native_decide

end IR370
